const {
  VITE_API_URL: API_URL,
  VITE_AUTH_DOMAIN: AUTH_DOMAIN,
  VITE_AUTH_CLIENT_ID: AUTH_CLIENT_ID,
  VITE_AUTH_AUDIENCE: AUTH_AUDIENCE
} = import.meta.env;

export { API_URL, AUTH_DOMAIN, AUTH_CLIENT_ID, AUTH_AUDIENCE };
